# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-05-18 06:48
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ccblog', '0002_user_logincount'),
    ]

    operations = [
        migrations.AddField(
            model_name='blog',
            name='lastModifyTime',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
